name: test workflow

on:
  - push
  - pull_request

jobs:
  test:
    name: test

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}
    env:
      DOTNET_NOLOGO: true
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install dotnemt
        uses: actions/setup-dotnet@v1
        with:
          node-version: '3.1.x'

      - name: install packages
        run: dotnet restore 

      - name: build
        run: dotnet build

      - name: test
        run: dotnet test